//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Article
{
    public int PostIDfk { get; set; }
    public System.Guid UserIDfk { get; set; }
    public string ArticleSummary { get; set; }
    public string ArticleContent { get; set; }
    public bool ArticleVisible { get; set; }

    public virtual Post Post { get; set; }
}

public partial class Comment
{
    public int CommentID { get; set; }
    public int PostIDfk { get; set; }
    public System.Guid UserIDfk { get; set; }
    public string CommentEmail { get; set; }
    public string CommentName { get; set; }
    public string CommentWebsite { get; set; }
    public string CommentText { get; set; }
    public string CommentDate { get; set; }

    public virtual Post Post { get; set; }
}

public partial class Course
{
    public Course()
    {
        this.CourseRegisters = new HashSet<CourseRegister>();
    }

    public int CourseID { get; set; }
    public string CourseTitle { get; set; }
    public string CourseLocation { get; set; }
    public string CourseDateStart { get; set; }
    public string CourseDateEnd { get; set; }
    public string CoursePicture { get; set; }
    public string CourseDES { get; set; }

    public virtual ICollection<CourseRegister> CourseRegisters { get; set; }
}

public partial class CourseRegister
{
    public int CourseRegisterID { get; set; }
    public int CourseIDfk { get; set; }
    public System.Guid UserIDfk { get; set; }
    public bool CourseActive { get; set; }
    public string FirtName { get; set; }
    public string LastName { get; set; }
    public string FatherName { get; set; }
    public bool Gender { get; set; }
    public string BirthDate { get; set; }
    public string PhoneNumber { get; set; }
    public string CellNumber { get; set; }
    public string Email { get; set; }
    public string Occupation { get; set; }
    public string LastDegree { get; set; }
    public string ShoShenasname { get; set; }
    public string SodourShenasname { get; set; }
    public string ShoMeli { get; set; }
    public string Address { get; set; }
    public string PassedPrerequisite { get; set; }
    public string PrerequisiteNumber { get; set; }
    public string Resume { get; set; }

    public virtual Course Course { get; set; }
}

public partial class HitCounter
{
    public int PostIDfk { get; set; }
    public int Counter { get; set; }

    public virtual Post Post { get; set; }
}

public partial class jQuery
{
    public int jQueryID { get; set; }
    public string jQueryTitle { get; set; }
    public string jQueryContent { get; set; }
    public string jQueryPicture { get; set; }
}

public partial class Miscellaneou
{
    public int PostIDfk { get; set; }
    public string MsSummary { get; set; }
    public string MsContent { get; set; }

    public virtual Post Post { get; set; }
}

public partial class Picture
{
    public Picture()
    {
        this.PicturesURLs = new HashSet<PicturesURL>();
    }

    public int PostIDfk { get; set; }
    public string PictureDES { get; set; }

    public virtual Post Post { get; set; }
    public virtual ICollection<PicturesURL> PicturesURLs { get; set; }
}

public partial class PicturesURL
{
    public int PictureID { get; set; }
    public int PicturePostIDfk { get; set; }
    public string PictureURL { get; set; }

    public virtual Picture Picture { get; set; }
}

public partial class Post
{
    public Post()
    {
        this.Comments = new HashSet<Comment>();
        this.Ratings = new HashSet<Rating>();
    }

    public int PostID { get; set; }
    public string PostType { get; set; }
    public string PostTitle { get; set; }
    public string PostDate { get; set; }
    public string PostPicture { get; set; }

    public virtual Article Article { get; set; }
    public virtual ICollection<Comment> Comments { get; set; }
    public virtual HitCounter HitCounter { get; set; }
    public virtual Miscellaneou Miscellaneou { get; set; }
    public virtual Picture Picture { get; set; }
    public virtual ICollection<Rating> Ratings { get; set; }
    public virtual Video Video { get; set; }
}

public partial class Rating
{
    public int RatingID { get; set; }
    public int PostIDfk { get; set; }
    public int TotalVoter { get; set; }
    public int RatingPreValue { get; set; }
    public byte RatingResult { get; set; }

    public virtual Post Post { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class UserProfile
{
    public System.Guid UserIDfk { get; set; }
    public string Name { get; set; }
    public string LastName { get; set; }
    public string Avatar { get; set; }
    public string About { get; set; }
    public string WebSite { get; set; }
    public string Email { get; set; }
    public string Messenger { get; set; }
}

public partial class Video
{
    public int PostIDfk { get; set; }
    public string VideoUrl { get; set; }
    public string VideoDES { get; set; }

    public virtual Post Post { get; set; }
}
